### PR TITLE
Add emoji to the pull request template

### PR DESCRIPTION
**Pull request by sleepylee**
## What happened

Add emoji to the pull request template
 
## Insight

Just want to make a PR less serious and express better on each section.
 
## Proof Of Work

You'll see after this is merged 💁‍♂️

### CODE REVIEW

**Comment by sleepylee** [comment]
POW
image

**Review by olivierobert — APPROVED** [review]
That deserves the crown for most import PR of 2020

**Comment by sleepylee** [comment]
important thing must go first, and fast

**Review by lydiasama — APPROVED** [review]

**Review by luongvo — APPROVED** [review]
lol, a big pr 💯

**Pull request merged**
